-- =========================================================
-- ZAPLOFT DATABASE
-- =========================================================
--
-- COMPLETE DATABASE FOR:
--
-- 1. Admin users
-- 2. Partner users
-- 3. Customers
-- 4. Campaigns
-- 5. Messages
-- 6. Partner website signup
-- 7. Razorpay payment verification
-- 8. Partner profile change approval
--
-- FLOW:
--
-- WEBSITE
--   ↓
-- SELECT PLAN
--   ↓
-- RAZORPAY PAYMENT
--   ↓
-- PAYMENT VERIFIED
--   ↓
-- PARTNER CREATE ACCOUNT
--   ↓
-- partner_signup_requests
--   ↓
-- ADMIN APPROVAL
--   ↓
-- users
--   ↓
-- PARTNER LOGIN
--
-- EXISTING PARTNER:
--
-- Partner Dashboard
--   ↓
-- Edit Profile
--   ↓
-- partner_profile_requests
--   ↓
-- Admin Approval
--   ↓
-- users updated
--
-- =========================================================



-- =========================================================
-- USERS
-- =========================================================
--
-- Stores actual authenticated users.
--
-- Roles:
--   ADMIN
--   PARTNER
--
-- Website signup does NOT create a users row
-- until admin approval.
-- =========================================================

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,

    name VARCHAR(150) NOT NULL,

    email VARCHAR(255) NOT NULL UNIQUE,

    password_hash TEXT NOT NULL,

    role VARCHAR(20) NOT NULL
        CHECK (
            role IN (
                'ADMIN',
                'PARTNER'
            )
        ),

    company_name VARCHAR(255),

    phone VARCHAR(30),

    profile_photo TEXT,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL
        DEFAULT CURRENT_TIMESTAMP
);


-- =========================================================
-- SAFE MIGRATION FOR EXISTING USERS TABLE
-- =========================================================

ALTER TABLE users
ADD COLUMN IF NOT EXISTS profile_photo TEXT;



-- =========================================================
-- CUSTOMERS
-- =========================================================

CREATE TABLE IF NOT EXISTS customers (
    id SERIAL PRIMARY KEY,

    partner_id INTEGER NOT NULL
        REFERENCES users(id)
        ON DELETE CASCADE,

    customer_name VARCHAR(255) NOT NULL,

    phone VARCHAR(30) NOT NULL,

    due_date VARCHAR(100),

    start_date VARCHAR(100),

    end_date VARCHAR(100),

    gender VARCHAR(30),

    age INTEGER,

    subscription VARCHAR(50),

    created_at TIMESTAMP NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL
        DEFAULT CURRENT_TIMESTAMP
);



-- =========================================================
-- CAMPAIGNS
-- =========================================================

CREATE TABLE IF NOT EXISTS campaigns (
    id SERIAL PRIMARY KEY,

    partner_id INTEGER NOT NULL
        REFERENCES users(id)
        ON DELETE CASCADE,

    template_name VARCHAR(255) NOT NULL,

    language_code VARCHAR(20)
        DEFAULT 'en',

    total_count INTEGER
        DEFAULT 0,

    accepted_count INTEGER
        DEFAULT 0,

    sent_count INTEGER
        DEFAULT 0,

    delivered_count INTEGER
        DEFAULT 0,

    failed_count INTEGER
        DEFAULT 0,

    created_at TIMESTAMP NOT NULL
        DEFAULT CURRENT_TIMESTAMP
);



-- =========================================================
-- MESSAGES
-- =========================================================

CREATE TABLE IF NOT EXISTS messages (
    id SERIAL PRIMARY KEY,

    partner_id INTEGER NOT NULL
        REFERENCES users(id)
        ON DELETE CASCADE,

    campaign_id INTEGER
        REFERENCES campaigns(id)
        ON DELETE SET NULL,

    customer_id INTEGER
        REFERENCES customers(id)
        ON DELETE SET NULL,

    phone VARCHAR(30) NOT NULL,

    template_name VARCHAR(255),

    message_id VARCHAR(500),

    status VARCHAR(50)
        DEFAULT 'pending',

    error TEXT,

    sent_at TIMESTAMP,

    delivered_at TIMESTAMP,

    failed_at TIMESTAMP,

    created_at TIMESTAMP NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL
        DEFAULT CURRENT_TIMESTAMP
);



-- =========================================================
-- PARTNER PAYMENT SESSIONS
-- =========================================================
--
-- Created BEFORE partner account creation.
--
-- Payment flow:
--
--   Solo / Pro / Business
--        ↓
--   Razorpay subscription
--        ↓
--   payment_token
--        ↓
--   Payment verified
--        ↓
--   Create account allowed
--
-- IMPORTANT:
--
-- PAID payment is required before partner signup.
--
-- payment_token is generated by our backend.
--
-- status:
--   PENDING
--   PAID
--   FAILED
--   EXPIRED
--
-- used_at prevents the same payment from being
-- used to create multiple partner accounts.
-- =========================================================

CREATE TABLE IF NOT EXISTS partner_payment_sessions (
    id SERIAL PRIMARY KEY,

    payment_token VARCHAR(100) NOT NULL UNIQUE,

    plan_key VARCHAR(30) NOT NULL,

    plan_name VARCHAR(100) NOT NULL,

    razorpay_plan_id VARCHAR(100) NOT NULL,

    razorpay_subscription_id VARCHAR(100),

    razorpay_payment_id VARCHAR(100),

    razorpay_signature TEXT,

    amount INTEGER,

    currency VARCHAR(10)
        NOT NULL DEFAULT 'INR',

    status VARCHAR(30)
        NOT NULL DEFAULT 'PENDING'
        CHECK (
            status IN (
                'PENDING',
                'PAID',
                'FAILED',
                'EXPIRED'
            )
        ),

    created_at TIMESTAMP NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    paid_at TIMESTAMP,

    used_at TIMESTAMP
);



-- =========================================================
-- SAFE MIGRATION FOR EXISTING PAYMENT TABLE
-- =========================================================

ALTER TABLE partner_payment_sessions
ADD COLUMN IF NOT EXISTS payment_token VARCHAR(100);

ALTER TABLE partner_payment_sessions
ADD COLUMN IF NOT EXISTS plan_key VARCHAR(30);

ALTER TABLE partner_payment_sessions
ADD COLUMN IF NOT EXISTS plan_name VARCHAR(100);

ALTER TABLE partner_payment_sessions
ADD COLUMN IF NOT EXISTS razorpay_plan_id VARCHAR(100);

ALTER TABLE partner_payment_sessions
ADD COLUMN IF NOT EXISTS razorpay_subscription_id VARCHAR(100);

ALTER TABLE partner_payment_sessions
ADD COLUMN IF NOT EXISTS razorpay_payment_id VARCHAR(100);

ALTER TABLE partner_payment_sessions
ADD COLUMN IF NOT EXISTS razorpay_signature TEXT;

ALTER TABLE partner_payment_sessions
ADD COLUMN IF NOT EXISTS amount INTEGER;

ALTER TABLE partner_payment_sessions
ADD COLUMN IF NOT EXISTS currency VARCHAR(10)
    DEFAULT 'INR';

ALTER TABLE partner_payment_sessions
ADD COLUMN IF NOT EXISTS status VARCHAR(30)
    DEFAULT 'PENDING';

ALTER TABLE partner_payment_sessions
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP
    DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE partner_payment_sessions
ADD COLUMN IF NOT EXISTS paid_at TIMESTAMP;

ALTER TABLE partner_payment_sessions
ADD COLUMN IF NOT EXISTS used_at TIMESTAMP;



-- =========================================================
-- PARTNER WEBSITE SIGNUP APPLICATIONS
-- =========================================================
--
-- Website:
--
--   zaploft.in
--       ↓
--   Solo / Pro / Business
--       ↓
--   Razorpay
--       ↓
--   Payment verified
--       ↓
--   Create Account
--       ↓
--   This table
--       ↓
--   PENDING
--       ↓
--   Admin approval
--       ↓
--   users
--
-- Email CANNOT be changed by partner.
--
-- Password is stored as bcrypt hash.
-- =========================================================

CREATE TABLE IF NOT EXISTS partner_signup_requests (
    id SERIAL PRIMARY KEY,

    payment_session_id INTEGER
        REFERENCES partner_payment_sessions(id)
        ON DELETE SET NULL,

    payment_token VARCHAR(100),

    plan_key VARCHAR(30),

    plan_name VARCHAR(100) NOT NULL,

    name VARCHAR(150) NOT NULL,

    email VARCHAR(255) NOT NULL,

    password_hash TEXT NOT NULL,

    company_name VARCHAR(255) NOT NULL,

    phone VARCHAR(30),

    profile_photo TEXT,

    status VARCHAR(20) NOT NULL
        DEFAULT 'PENDING'
        CHECK (
            status IN (
                'PENDING',
                'APPROVED',
                'REJECTED'
            )
        ),

    admin_id INTEGER
        REFERENCES users(id)
        ON DELETE SET NULL,

    admin_note TEXT,

    created_at TIMESTAMP NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    reviewed_at TIMESTAMP
);


-- =========================================================
-- SAFE MIGRATION FOR EXISTING SIGNUP TABLE
-- =========================================================

ALTER TABLE partner_signup_requests
ADD COLUMN IF NOT EXISTS payment_session_id INTEGER;

ALTER TABLE partner_signup_requests
ADD COLUMN IF NOT EXISTS payment_token VARCHAR(100);

ALTER TABLE partner_signup_requests
ADD COLUMN IF NOT EXISTS plan_key VARCHAR(30);



-- =========================================================
-- PARTNER PROFILE CHANGE REQUESTS
-- =========================================================
--
-- Used AFTER partner account exists.
--
-- Partner may request:
--
--   name
--   company_name
--   phone
--   profile_photo
--   password
--
-- Partner CANNOT change:
--
--   email
--   role
--   is_active
--
-- Flow:
--
--   Partner Settings
--        ↓
--   Submit Changes
--        ↓
--   PENDING
--        ↓
--   Admin Profile Requests
--        ↓
--   APPROVE
--        ↓
--   users updated
-- =========================================================

CREATE TABLE IF NOT EXISTS partner_profile_requests (
    id SERIAL PRIMARY KEY,

    partner_id INTEGER NOT NULL
        REFERENCES users(id)
        ON DELETE CASCADE,

    requested_name VARCHAR(150) NOT NULL,

    requested_company_name VARCHAR(255),

    requested_phone VARCHAR(30),

    requested_profile_photo TEXT,

    requested_password_hash TEXT,

    status VARCHAR(20) NOT NULL
        DEFAULT 'PENDING'
        CHECK (
            status IN (
                'PENDING',
                'APPROVED',
                'REJECTED'
            )
        ),

    admin_id INTEGER
        REFERENCES users(id)
        ON DELETE SET NULL,

    admin_note TEXT,

    created_at TIMESTAMP NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    reviewed_at TIMESTAMP
);



-- =========================================================
-- INDEXES
-- =========================================================


-- =========================================================
-- USERS
-- =========================================================

CREATE INDEX IF NOT EXISTS
idx_users_role
ON users(role);



-- =========================================================
-- CUSTOMERS
-- =========================================================

CREATE INDEX IF NOT EXISTS
idx_customers_partner
ON customers(partner_id);

CREATE INDEX IF NOT EXISTS
idx_customers_phone
ON customers(phone);



-- =========================================================
-- CAMPAIGNS
-- =========================================================

CREATE INDEX IF NOT EXISTS
idx_campaigns_partner
ON campaigns(partner_id);



-- =========================================================
-- MESSAGES
-- =========================================================

CREATE INDEX IF NOT EXISTS
idx_messages_partner
ON messages(partner_id);

CREATE INDEX IF NOT EXISTS
idx_messages_customer
ON messages(customer_id);

CREATE INDEX IF NOT EXISTS
idx_messages_campaign
ON messages(campaign_id);

CREATE INDEX IF NOT EXISTS
idx_messages_message_id
ON messages(message_id);



-- =========================================================
-- PAYMENT SESSIONS
-- =========================================================

CREATE UNIQUE INDEX IF NOT EXISTS
idx_partner_payment_sessions_token
ON partner_payment_sessions(payment_token);

CREATE INDEX IF NOT EXISTS
idx_partner_payment_sessions_plan
ON partner_payment_sessions(plan_key);

CREATE INDEX IF NOT EXISTS
idx_partner_payment_sessions_status
ON partner_payment_sessions(status);

CREATE UNIQUE INDEX IF NOT EXISTS
idx_partner_payment_sessions_subscription
ON partner_payment_sessions(
    razorpay_subscription_id
)
WHERE razorpay_subscription_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS
idx_partner_payment_sessions_created
ON partner_payment_sessions(created_at);



-- =========================================================
-- PARTNER SIGNUP REQUESTS
-- =========================================================

CREATE INDEX IF NOT EXISTS
idx_partner_signup_requests_email
ON partner_signup_requests(email);

CREATE INDEX IF NOT EXISTS
idx_partner_signup_requests_status
ON partner_signup_requests(status);

CREATE INDEX IF NOT EXISTS
idx_partner_signup_requests_created
ON partner_signup_requests(created_at);

CREATE INDEX IF NOT EXISTS
idx_partner_signup_requests_payment_token
ON partner_signup_requests(payment_token);

CREATE INDEX IF NOT EXISTS
idx_partner_signup_requests_payment_session
ON partner_signup_requests(payment_session_id);

CREATE INDEX IF NOT EXISTS
idx_partner_signup_requests_plan
ON partner_signup_requests(plan_key);



-- =========================================================
-- PARTNER PROFILE REQUESTS
-- =========================================================

CREATE INDEX IF NOT EXISTS
idx_partner_profile_requests_partner
ON partner_profile_requests(partner_id);

CREATE INDEX IF NOT EXISTS
idx_partner_profile_requests_status
ON partner_profile_requests(status);

CREATE INDEX IF NOT EXISTS
idx_partner_profile_requests_created
ON partner_profile_requests(created_at);



-- =========================================================
-- ONE PENDING PAYMENT PER TOKEN
-- =========================================================

CREATE UNIQUE INDEX IF NOT EXISTS
idx_partner_payment_sessions_token_unique
ON partner_payment_sessions(payment_token);



-- =========================================================
-- ONE PENDING SIGNUP PER EMAIL
-- =========================================================

CREATE UNIQUE INDEX IF NOT EXISTS
idx_one_pending_signup_per_email
ON partner_signup_requests(
    LOWER(email)
)
WHERE status = 'PENDING';



-- =========================================================
-- ONE PENDING PROFILE REQUEST PER PARTNER
-- =========================================================

CREATE UNIQUE INDEX IF NOT EXISTS
idx_one_pending_profile_request_per_partner
ON partner_profile_requests(partner_id)
WHERE status = 'PENDING';



-- =========================================================
-- VERIFY TABLES
-- =========================================================

SELECT
    table_name
FROM information_schema.tables
WHERE
    table_schema = 'public'
    AND table_name IN (
        'users',
        'customers',
        'campaigns',
        'messages',
        'partner_payment_sessions',
        'partner_signup_requests',
        'partner_profile_requests'
    )
ORDER BY table_name;



-- =========================================================
-- VERIFY USERS COLUMNS
-- =========================================================

SELECT
    column_name,
    data_type
FROM information_schema.columns
WHERE
    table_schema = 'public'
    AND table_name = 'users'
ORDER BY ordinal_position;



-- =========================================================
-- VERIFY PAYMENT SESSION COLUMNS
-- =========================================================

SELECT
    column_name,
    data_type
FROM information_schema.columns
WHERE
    table_schema = 'public'
    AND table_name = 'partner_payment_sessions'
ORDER BY ordinal_position;



-- =========================================================
-- VERIFY PARTNER SIGNUP COLUMNS
-- =========================================================

SELECT
    column_name,
    data_type
FROM information_schema.columns
WHERE
    table_schema = 'public'
    AND table_name = 'partner_signup_requests'
ORDER BY ordinal_position;



-- =========================================================
-- VERIFY PROFILE REQUEST COLUMNS
-- =========================================================

SELECT
    column_name,
    data_type
FROM information_schema.columns
WHERE
    table_schema = 'public'
    AND table_name = 'partner_profile_requests'
ORDER BY ordinal_position;
